#!/bin/bash

git clone --bare git@github.com:jPrest/dotfiles.git $HOME/.cfg

function config {
  git --git-dir=$HOME/.cfg/ --work-tree=$HOME $@  
}

config checkout
config config status.showUntrackedFiles no
