#!/bin/bash

env=~/.ssh/agent.env

agent_load_env () {
  test -f "$env" && source "$env" > /dev/null
}

agent_start() {
  ssh-agent > "$env"
}

agent_load_env
agent_run_state=$(ssh-add -l 2>/dev/null; echo $?)

# agent_run_state: 0=agent running w/ key; 1=agent w/o key; 2= agent not running
if [ ! "$SSH_AUTH_SOCK" ] || [ "$agent_run_state" = 2 ]; then
  echo "starting ssh agent"
  agent_start
  agent_load_env
  ssh-add
elif [ "$SSH_AUTH_SOCK" ] && [ "$agent_run_state" = 1 ]; then
  ssh-add
fi

unset env